apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
type: Opaque
data:
  #
  # TIP: Use `echo -n VALUE | base64` to encode raw secret value.
  #
  OAUTH2_PROXY_CLIENT_ID: "<REPLACE_ME>"
  OAUTH2_PROXY_CLIENT_SECRET: "<REPLACE_ME>"
  OAUTH2_PROXY_COOKIE_SECRET: "<REPLACE_ME>"
