---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app1-cert
spec:
  secretName: app1-ingress-tls
  dnsNames:
    - app1.supercorp.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
